### PR TITLE
build.zig: Fix thisDir for relative @src().file

### PR DESCRIPTION
**Pull request by Luexa**
While normal `zig build` invocations will continue to have absolute paths for `@src.file`, when invoked by ZLS (at least on my own system; NixOS x86_64) it actually returns a relative path, breaking this project's assumption that `thisDir` is absolute. The result is that ZLS *crashes entirely*, so without this fix `zig-flecs` will be completely unusable in my workflow.

This PR fixes the issue by calculating a `projectPath` at runtime, allocating memory and/or resolving paths if the result of `@src().file` is non-absolute. This will require dependent projects to invoke `flecs.pkg(b)` at runtime instead of simply adding a comptime-known `flecs.pkg`, but it is a necessary evil to allow the project to compile with a relative `@src().file`.

### CODE REVIEW

**Comment by foxnne** [comment]
Thanks for the PR! But if its alright, I might want to look into this a bit... [Example of zig-gamedev lib build.zig](https://github.com/michal-z/zig-gamedev/blob/cb46c095dcbf1e86361cde4d6d12ab32ef691842/libs/zgui/build.zig#L81), all of zig-gamedev seems to follow this pattern and I haven't seemed to have any issue using this on macOS or Windows. I'm wondering if this is only an issue for NixOS?

Linking to [#179](https://github.com/michal-z/zig-gamedev/pull/179) for clarity.

**Comment by Luexa** [comment]
I'm working on a PR for zig-gamedev and Mach engine as well for the same
issue. zig-flecs is one of several dependencies that caused ZLS to crash.

**Comment by foxnne** [comment]
Okay! I just saw that and edited my comment to link in that issue. If its okay, I just want to see if Michal has any other ideas for this or if this solution is good as is, eventually zig-flecs will likely be absorbed into zig-gamedev I believe, and want to follow whatever solution lands there.

**Comment by Luexa** [comment]
Yeah that is reasonable. Just wanted to raise awareness of this issue to
figure out a proper fix for it. Difficult if no one is able to reproduce it
though.

**Comment by foxnne** [comment]
I brought this up in the ZLS discord server and it looks like the fix is going to make it into ZLS soon, which would remove the need for this change.

https://github.com/zigtools/zls/pull/898

**Comment by Luexa** [comment]
Understood. I figured ZLS could use cwd to force path to be absolute, but I
feel this method as a whole is brittle no matter how it's implemented. But
that's out of scope of this discussion.

**Comment by Luexa** [comment]
Closing due to this behavior being worked around by ZLS (https://github.com/zigtools/zls/pull/898)

**Pull request closed without merging**
